### ISSUE TITLE
support waiting for test.run()

### ISSUE THREAD

**Issue by hardfist** [lukeed/uvu#221] opened 2022-09-15 06:26 UTC
I want to generate test case on the fly, but it seems I can't wait wait for the dynamic case finished by waiting test.run()
```js
const { test } = require('uvu');
const assert = require('assert');
test("hello", () => {
  console.log('middle');
  assert.equal(1,1);
})
async function main(){
  console.log("begin");
  await test.run(); // not working
  console.log('end');
}

main();

```

**Comment by lukeed** [comment] 2022-09-15 06:37
Yep, it’s planned. Duplicate of #38

**Closed by lukeed** 2022-09-15 06:37 UTC
