### ISSUE TITLE
unclear date diff

### ISSUE THREAD

**Issue by alextes** [lukeed/uvu#176] opened 2021-12-09 23:12 UTC
I wrote the following test for uvu in `test/diff.js` that currently passes:
```js
compare('should handle date diff', () => {
	assert.snapshot(
		strip($.compare(new Date(0), new Date(1))),
		'++"1970-01-01T00:00:00.001Z"    (Expected)\n' +
		'--                        {}    (Actual)\n' +
		'  ^^^^^^^^^^^^^^^^^^^^^^^^^^'
	)
})
```

Somehow the second date disappears into a `{}`.

Screenshot for clarity:
<img width="745" alt="Screenshot 2021-12-09 at 17 10 33" src="https://user-images.githubusercontent.com/2011351/145490214-f02d0674-f9b5-4290-9cd6-8cdb378de974.png">

Took me a while to figure out the test output was correct in saying my dates don't match, but it took me a while to figure out as the second date isn't printed, which I'm guessing is not the intention.

**Comment by rschristian** [comment] 2021-12-17 01:25
Duplicate of #92

**Closed** 2021-12-19 17:59 UTC
Labels: duplicate
