### ISSUE TITLE
Feature Request: updated `.fixture` diffing

### ISSUE THREAD

**Issue by jasikpark** [lukeed/uvu#128] opened 2021-08-04 19:28 UTC
The current output of `assert.fixture(formatted,out)` isn't very intelligible to me currently:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/10626596/128242761-a45d2d1b-d3d3-4ea3-b07e-66931520b3ca.png">

I ended up just printing out the values side by side so I could actually *see* the difference in formatting between them..

Would it be possible to use a more advanced diffing output that looks similar to [`delta`](https://github.com/dandavison/delta)?

example:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/10626596/128243469-2a671c41-944a-4000-9339-b80ebda9e19b.png">

It'd be nice if it was possible to just *use* delta, but it's written in rust and I doubt they publish a WASM npm package.

**Comment by jasikpark** [comment] 2021-08-04 19:33
I suppose a difference between the two is that `delta` is doing a diff that assumes there might be code inside whereas uvu is assuming that the strings are random structureless data?

**Comment by lukeed** [comment] 2021-08-04 23:12
I looked at relying on a `delta` installation already being installed on the host machine, but it wasn't a good idea in terms of practicality. It would have also made uvu the only JS test runner to have a non-JS system peer dependency... and either at that point, or with a WASM integration, you start dancing around the "why use JS at all" question/territory.

That aside, the two screen shots you have are saying the exact same thing. The only real difference is that `uvu`'s is using text color while delta's is highlighting the line with red/green backgrounds.

The other _diff_ difference is that uvu detected missing new lines before the `<style>` tag & the other one doesn't. My guess is that you/something compensated for that as part of creating the `formatted-rename-me.astro` file creation

**Comment by jasikpark** [comment] 2021-08-05 00:23
I can understand that they mean the same thing, but the delta output with color background and the brighter background color to denote spaces makes more sense to me - I couldn't figure out what the top part of extra returns was and seeing what the difference in whitespace was between the two..

You're right - I failed to copy the top two returns when copying to a file 👍

**Comment by lukeed** [comment] 2021-08-05 02:43
I'd consider highlighting the whitespace difference. I mean, to me, it's pretty clear that one is more indented than the other, but highlighting could help in some cases perhaps.

Fwiw, jest has the same whitespace display as I do (no highlight) and some would say that's the expectation/standard now.

Closing as duplicate of #1 as in general that ticket is about more control over diffing.

Thanks :)

**Closed by lukeed** 2021-08-05 02:43 UTC

**Comment by jasikpark** [comment] 2021-08-05 03:14
Thanks for talking about it! I'll follow #1
