### ISSUE TITLE
Strange error without error message

### ISSUE THREAD

**Issue by ai** [lukeed/uvu#153] opened 2021-11-01 16:38 UTC
[Repo](https://github.com/nanostores/nanostores/tree/uvu)

I can run every test file without any problem:

```sh
$ npx tsm node_modules/uvu/bin.js . action/index.test.ts
(node:87231) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:87231) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
action/index.test.ts
• • • • •   (5 / 5)

  Total:     5
  Passed:    5
  Skipped:   0
  Duration:  22.89ms
```

But when I run all files, test stops in the middle with strange output:

```sh
npx tsm node_modules/uvu/bin.js . .test.ts            
(node:87500) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:87500) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, transformSource
action/index.test.ts
• • %
```

**Comment by ai** [comment] 2021-11-01 16:40
Error repeats on every Node.js version: https://github.com/nanostores/nanostores/runs/4070320440?check_suite_focus=true

**Comment by lukeed** [comment] 2021-11-01 17:35
This is a duplicate of https://github.com/lukeed/uvu/issues/99

You're using:

```js
import FakeTimers from '@sinonjs/fake-timers'

// ...

let clock = FakeTimers.install()
```

If you remove/rename any test files that have this within them, uvu works as expected.
And if you follow the linked issue, you'll see a workaround for this. The `FakeTimers` **completely** takes over & mutates the entire process, which is a horrible thing to do. In doing that, anything else that relies on `setTimeout`/etc is at the mercy of `FakeTimers`, including uvu.

It doesn't throw an error or anything else, so it's not a lack of reporting. It's literally sinon taking over & pausing all uvu execution.

**Closed by lukeed** 2021-11-01 17:35 UTC

**Comment by lukeed** [comment] 2021-11-01 17:37
If you still want/need to use the sinon timers, I (still) recommend the last snippet from here: https://github.com/lukeed/uvu/issues/99#issuecomment-788223855

**Comment by ai** [comment] 2021-11-01 17:43
Thanks.

Maybe you know a good alternative to test code with very long timers? I do not need Sinon specifically.

**Comment by lukeed** [comment] 2021-11-01 17:52
I don't dude, sorry :/ I don't write tests this way so it's not something on my radar. That last snippet with the `test.before/test.after` blocks is the best way I know – I played with it when the last issue came up and it worked well ... it's always what/how SinonJS recommends to use its timers stub.
