### ISSUE TITLE
TypeScript and ESM

### ISSUE THREAD

**Issue by ai** [lukeed/uvu#123] opened 2021-06-30 05:07 UTC
[TypeScript example](https://github.com/lukeed/uvu/tree/master/examples/typescript) doesn’t work for my project with:

1. Sources in JS ESM (to avoid compiler)
2. Tests in TypeScript ESM
3. `"type": "module"` in `package.json`

[Repository to reproduce the error](https://github.com/ai/nanodelay/tree/uvu).

```
$ git clone git@github.com:ai/nanodelay.git
$ git checkout uvu
$ yarn
$ yarn test
uvu -r ts-node/register test && eslint . && check-dts && size-limit && yaspeller *.md
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ai/Dev/nanodelay/test/index.test.ts
require() of ES modules is not supported.
require() of /home/ai/Dev/nanodelay/test/index.test.ts from /home/ai/Dev/nanodelay/node_modules/ts-node/dist/index.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /home/ai/Dev/nanodelay/package.json.

    at createErrRequireEsm (/home/ai/Dev/nanodelay/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:86:15)
    at assertScriptCanLoadAsCJSImpl (/home/ai/Dev/nanodelay/node_modules/ts-node/dist-raw/node-cjs-loader-utils.js:19:11)
    at Object.require.extensions.<computed> [as .ts] (/home/ai/Dev/nanodelay/node_modules/ts-node/src/index.ts:1288:5)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at /home/ai/Dev/nanodelay/node_modules/uvu/run/index.js:9:3
    at Array.forEach (<anonymous>)
    at Object.exports.run (/home/ai/Dev/nanodelay/node_modules/uvu/run/index.js:6:9)
```

Removing `"type": "module"` from `package.json` solves the problem, but break my no compiler workflow.

**Comment by lukeed** [comment] 2021-06-30 05:51
I can make a PR tomorrow but you should be using esbuild. TS has no ESM support, so trying to use ts/ts-node alongside native ESM is just not going to work. There are experimental loader hooks from the ts-node side, but when I checked a few months ago it didn't work

**Comment by ai** [comment] 2021-06-30 05:56
BTW, `ts-node` loader was fixed. I used it to run my TS ESM server and `ts-node` recommends using loader for `ava`.

**Comment by lukeed** [comment] 2021-06-30 06:31
I'll check it out again. In any event, any use of -r/--require triggers the CJS mode of uvu. There's no --loader flag because there's no (stable) Node flag either. You need a -r because, sorry, you're still compiling. It's just on the fly, but require hook is the only way to convert your TS as needed.

If you have ts-node working, you can try importing these `ts-node`-specific config changes: https://github.com/lukeed/uvu/blob/master/examples/typescript/tsconfig.json#L5
Because you're in CJS mode, module format output has to change. If ts-node is not able to go back & forth due to the `type: module` then you'll have to go with esbuild-register

Will try it all tomorrow once I'm back to a computer, but wanted to leave a note before heading to bed

**Comment by ai** [comment] 2021-06-30 06:33
The special `tsconfig.json` for `ts-node` with `conmonjs` doesn't work unfortunately (works only if I will remove `type: module` from `package.json`)

**Comment by hgl** [comment] 2021-07-02 03:33
I can successfully run a test file under nodejs using`ts-node`'s ESM loader. It'd be nice if the `loader` flag could supported in the CLI.

**Comment by talentlessguy** [comment] 2021-07-07 13:17
another way would be using [esbuild-node-loader](https://github.com/antfu/esbuild-node-loader):

```sh
node --experimental-loader esbuild-node-loader node_modules/uvu/bin.js tests
```

I currently use that in most of my libraries

**Comment by alextes** [comment] 2021-08-08 11:13
the above was helpful.
`yarn esmo node_modules/uvu/bin.js tests` is not too bad.

Could we get slightly better support for running tests transpiled with esbuild-node-loader or a similar loader?

After spending two hours on this the warning for the unstable flag is the least of my worries and the ESM stuff seems to move v. slowly judging from the relevant issues I've read in node, ts-node, jest, ava, browserify/resolve repos. This all gives me more trouble with Ava & Jest. Honestly considering going back to CJS at this point 😅 .

For now though, just making the above command a bit shorter by supporting running with one of the many lovely loaders people have written (esmo, esrun) would be lovely.

**Comment by alextes** [comment] 2021-08-08 12:20
eehhh, no, not quite. Still didn't work.
With:
* ts
* compiled to esm
* source code imports look like: `import .. from "./my_esm.js"`
* esmo / esbuild-node-loader doesn't work

but that seems to do with esbuild-node-loader not supporting esm imports (I'm v. confused why https://github.com/antfu/esno/issues/10) but no matter, it finally got it to work like this: `node --experimental-loader ts-node/esm node_modules/uvu/bin.js src '.*.test.ts'`.

After thinking about it a bunch, I have no idea why that works, or if this invocation could be simplified somehow. Thinking through how `npm uvu ..` could still work I'm honestly not sure 🙈 .

**Comment by lukeed** [comment] 2021-08-08 16:53
uvu won't be adding loader support while ESM loaders are still marked as experimental. It's not a good time investment, especially since the current [node docs say](https://nodejs.org/api/esm.html#esm_loaders) that the loader API _will_ be reworked.

Loader support will be quickly added soon after its experimental notice is dropped.

You're all importing a bunch of tooling anyway, btw, and you seem to be fine with using it, so I'd use it one of two ways:

1) transpile to plain JS with ESM format, and then test _those_ files. You can delete them all as a `posttest` script for automatic cleanup

2) transpile to CJS on the fly, using the require hook. This approach is time-tested and is reliable. Existing tools, especially esbuild, make an effort to have 1:1 equivalence across formats. Of them all, esbuild makes an effort to be the most strictly compliant

**Comment by alextes** [comment] 2021-08-09 12:29
thanks for the clear answer @lukeed , sounds like 2. is what I should try!

.. a bit later

* converted all imports to CJS `import .. from "./lib"`
* downgraded a lib that was ESM-only already 😭 (p-queue)
* `yarn uvu -r ts-node/register src ".*.test.ts"` works!

Thanks for a great testing framework @lukeed , been dying for a light one.

**Comment by lukeed** [comment] 2021-08-09 13:19
You shouldn't need to downgrade if you're going with either of these approaches. I use (2) with pure ESM dependencies/source code very often. For me it's just `uvu -r esbuild-register tests` with a proper tsconfig file

**Comment by dominikg** [comment] 2021-08-12 18:03
What exactly is that proper tsconfigfile @lukeed? i've tried to use the [tsconfig from the esbuild example](https://github.com/lukeed/uvu/blob/master/examples/esbuild/tsconfig.json) here: https://github.com/dominikg/tsconfck

but i'm getting this when running `pnpm test` 
```
> uvu -r esbuild-register tests

/home/dominikg/develop/tsconfck/tests/find-tsconfig.ts:1
import { test } from "uvu";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Module._compile (/home/dominikg/develop/tsconfck/node_modules/.pnpm/esbuild-register@2.6.0/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at extensions..js (/home/dominikg/develop/tsconfck/node_modules/.pnpm/esbuild-register@2.6.0/node_modules/esbuild-register/dist/node.js:2696:24)
    at Object.newLoader [as .ts] (/home/dominikg/develop/tsconfck/node_modules/.pnpm/esbuild-register@2.6.0/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
 ERROR  Test failed. See above for more details.
```

**Comment by dominikg** [comment] 2021-08-13 10:40
The above problem is caused by `"type": "module"` in package.json. If you add that to the esbuild example the same error happens.
I worked around it in tsconfck by adding a package.json with `"type":"commonjs"` to the tests directory.
Unfortunately this leads to another problem where you can't import the code under test from src, so i'm importing that from `../dist/index.cjs` instead.

Would love to see a clean example with ts + module.

**Comment by ai** [comment] 2021-08-13 11:20
> converted all imports to CJS import .. from "./lib"
> downgraded a lib that was ESM-only already (p-queue)

It will be a big blocker for me.

Native ESM support is critical for modern Node.js projects. If test library just transpile it to CJS before running, I can’t be sure that my ESM code is correct (for instance, that I didn’t forget `__dirname` somewhere).

**Comment by alextes** [comment] 2021-08-15 18:31
ya fwiw, it turned out a big enough blocker for me too @ai to go back to ESM.

2. doesn't seem to work for me, I'm back to this beast `node --experimental-loader ts-node/esm node_modules/uvu/bin.js src '.*.test.ts'`
![Screenshot 2021-08-15 at 20 30 59](https://user-images.githubusercontent.com/2011351/129488726-15ea4c9c-2f4a-4932-b1d2-6a74df130ac4.png)

**Comment by wooorm** [comment] 2021-08-16 16:31
I recently had a similar issue with JSX in ESM and wrote a tiny node loader: https://github.com/remarkjs/react-markdown/blob/main/test/loader.js.

@lukeed while Node ESM loaders are experimental, the `require.extensions` mechanism is deprecated. While `require.extensions` of course isn’t likely to go away any time soon, and loaders are indeed as you say supposed to change, they at least provide a good enough basis for now to at least make the ESM experience much better.
(time investment might be a good reason to not do it though, I’m unsure how much work it would take and I can’t quickly estimate from browsing through the source. Alternatively documenting @alextes’ workaround in the readme might be an adequate solution?)

**Comment by lukeed** [comment] 2021-08-16 16:42
@wooorm Thanks :) I decided this weekend to start put together a loader CLI that will make dealing with all this easier; hopefully. This way the time/work is sanboxed to that specific tool & doesnt spill over into uvu directly, which is nice because loaders (and their issues, let alone their instability) affect all packages equally.

And `require.extensions` has been deprecated since Node 0.10 lol – it's never going away because it's simply too useful. They don't/can't work with ESM at all, but a big void in the loaders design is that they don't allow you can programmatically attach loader during runtime – I'm sure it's a design decision, but it's extremely clunky to force all users to **only** be able to define loaders externally, via `node` options directly.

It's.. rough.

**Comment by wooorm** [comment] 2021-08-16 16:51
Given that node loaders can be combined (https://github.com/node-loader/node-loader-core does this), then it’s perhaps also possible to do this dynamically at runtime in one loader?
Maybe uvu itself could also function as a node loader (`node --experimental-loader uvu test.js`)? 🤔
Might be too much of a deviation and investment but perhaps that could side-step the runtime attaching?

**Comment by lukeed** [comment] 2021-08-16 16:58
> `node --experimental-loader uvu test.js`

This was my first idea & is what sparked my "not worth the investment" comment (not until stable, at least). I also ended up here since `uvu --loader foobar tests` is currently impossible (which relates to my last comment re: lacking programmatic definitions)

The tool I'm building will allow for this:

```sh
$ thingy -- uvu tests
$ thingy -c custom.config.mjs -- uvu tests
```

Work week looks busy, but will be done by the weekend if can't find time sooner.

**Comment by wooorm** [comment] 2021-08-16 17:04
Ah yes.
That sounds interesting. No rush from me because @alextes’ workaround works fine. But looking forward to it!

**Comment by lukeed** [comment] 2021-08-17 07:42
I just finished putting together [`loadr`](https://github.com/lukeed/loadr), which is the `thingy` in my snippet above 😆 

With it, @alextes' example can be change from:

```sh
$ node --experimental-loader ts-node/esm node_modules/uvu/bin.js src '.*.test.ts'
```

to

```sh
$ loadr -- npm test
# assumes "test": "uvu src '.*.test.ts'"
```

It just needs a `loadr.mjs` configuration file:

```js
export const loaders = ['ts-node/esm'];
```

Of course, your `test` command could also include the `loadr` command directly:

```js
// package.json
{
  "scripts": {
    "test": "loadr -- uvu src '.*.test.ts'"
  }
}
```

This doesn't change anything about the original ESM + TS issue, but it's just a tool to cleanup the absurd amount of CLI paths and/or `--experimental-loader` flags you're throwing around 😆

**Comment by wooorm** [comment] 2021-08-17 10:41
Nice!

**Closed** 2021-10-05 06:27 UTC
